
name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: browsanka-windows
            runner: self-hosted # Assuming self-hosted for Windows
            spec_file: BROWSANKA.spec
            asset_path_suffix: BROWSANKA.exe
          - os: ubuntu-latest
            artifact_name: browsanka-linux
            runner: ubuntu-latest
            spec_file: BROWSANKA.spec
            asset_path_suffix: BROWSANKA
          - os: macos-latest
            artifact_name: browsanka-macos
            runner: macos-latest
            spec_file: BROWSANKA.spec
            asset_path_suffix: BROWSANKA
    runs-on: ${{ matrix.runner }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: python -m pip install --upgrade pip pipenv wheel pyinstaller

    - name: Build executable
      run: pyinstaller ${{ matrix.spec_file }}

    - name: List dist directory
      run: ls -R dist/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted # Assuming self-hosted for release
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/browsanka-windows/BROWSANKA.exe
            ./artifacts/browsanka-linux/BROWSANKA
            ./artifacts/browsanka-macos/BROWSANKA
